### ISSUE TITLE
Title Problem

### ISSUE THREAD

**Issue by RealEzra** [killer549/TimerPlus#1]
I noticed when installing your plugin using sheep at https://poggit.pmmp.io/p/TimerPlus/1.1.0 That there is a space after TimerPlus so I had to install like this install TimerPlus  1.1.0 instead of install TimerPlus 1.1.0 if you notice in the first one there is 2 space between the s and the 1

**Comment by ahmedhozny** [comment]
TimerPlus 1.1.0 hasn't been released until now in this section https://poggit.pmmp.io/plugins
Sheep does only support released plugins.
You may ask then why adding two spaces works. This is because the second space is considered by the server as an empty argument which means you didn't insert any value in this [version] .

**Comment by ahmedhozny** [comment]
I think that you will see this when adding two spaces `Loading TimerPlus v1.0.0-beta`. This is currently the version released on poggit.

Please notify me if u think I'm wrong about something.
